### PR TITLE
fix: always return client_id, require origin and simplify dc response

### LINKED ISSUE #32: Strip / replace `client_id` in oid4vp authorization request if using DC API
When using `dc_api` as response and the request is not signed, the `client_id` MUST NOT be present, but also MUST BE ignored. To prevent users of this library from leveraging an incorrect client_id I think we should do one of two:
- Remove the client_id from the payload that is returned by validate/resolve/parse methods
- Update the client_id to the effective client_id (`web-origin:${origin}`).

Also we should make sure the client id returned by the parse method ALWAYS returns a client id. This will make it easier to rely on the client_id returned from that method.

This applies to PR #21

### PR DESCRIPTION
**Pull request by TimoGlastra**
Fixes #32 #38

### CODE REVIEW

File: packages/openid4vp/src/authorization-request/z-authorization-request-dc-api.ts [hunk 1]
```diff
@@ -23,7 +22,7 @@ export const zOpenid4vpAuthorizationRequestDcApi = zOpenid4vpAuthorizationReques
 export type Openid4vpAuthorizationRequestDcApi = z.infer<typeof zOpenid4vpAuthorizationRequestDcApi>
 
 export function isOpenid4vpAuthorizationRequestDcApi(
-  request: Openid4vpAuthorizationRequest | JarAuthRequest | Openid4vpAuthorizationRequestDcApi
```
Comment (auer-martin) [inline packages/openid4vp/src/authorization-request/z-authorization-request-dc-api.ts:26]: If you only have the raw response parameters and don't know if jar was used or not, might it be helpful to keep the JarAuthRequest?

File: packages/openid4vp/src/vp-token/z-vp-token.ts [hunk 2]
```diff
@@ -1,4 +1,8 @@
 import { z } from 'zod'
 
-export const zVpToken = z.union([z.string(), z.array(z.string()), z.record(z.string(), z.unknown())])
+export const zVpToken = z.union([
+  z.string(),
+  z.array(z.union([z.string(), z.record(z.any())])),
```
Comment (auer-martin) [inline packages/openid4vp/src/vp-token/z-vp-token.ts:5]: why any?

**Review by auer-martin — APPROVED** [review]

File: packages/openid4vp/src/vp-token/z-vp-token.ts (hunk 2 above)
Comment (TimoGlastra) [reply packages/openid4vp/src/vp-token/z-vp-token.ts:5]: Hmm I just had quite some issues in credo with hasving to cast types, while basically we just want to accept any object like structure. I can  check if unknown also works
